[tool.poetry]
name = "quartical"
version = "0.2.0"
description = "Fast and flexible calibration suite for radio interferometer data."
repository = "https://github.com/ratt-ru/QuartiCal"
documentation = "https://quartical.readthedocs.io"
authors = ["Jonathan Kenyon <jonathan.simon.kenyon@gmail.com>"]
license = "MIT"
readme = "README.md"
classifiers = [
    "Development Status :: 4 - Beta",
    "Intended Audience :: Science/Research",
    "License :: OSI Approved :: MIT License",
    "Operating System :: POSIX :: Linux",
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3.8",
    "Programming Language :: Python :: 3.9",
    "Programming Language :: Python :: 3.10",
    "Topic :: Scientific/Engineering :: Astronomy"
]
include = [
    "quartical/config/argument_schema.yaml",
    "quartical/config/gain_schema.yaml",
    "quartical/stimela_cabs.yaml"
]

[tool.poetry.dependencies]
python = "^3.9, < 3.13"
tbump = "^6.10.0"
columnar = "^1.4.1"
"ruamel.yaml" = "^0.17.26"
dask = {extras = ["diagnostics"], version = "^2023.1.0"}
distributed = "^2023.1.0"
dask-ms = {git = "https://github.com/ratt-ru/dask-ms.git", extras = ["s3", "xarray", "zarr"], branch="master"}
codex-africanus = {extras = ["dask", "scipy", "astropy", "python-casacore"], version = "^0.3.4"}
astro-tigger-lsm = "^1.7.2"
loguru = "^0.7.0"
requests = "^2.31.0"
pytest = "^7.3.1"
omegaconf = "^2.3.0"
colorama = "^0.4.6"
stimela = {git = "https://github.com/caracal-pipeline/stimela", branch = "FIASCO3"}
ducc0 = "^0.31.0"
sympy = "^1.12"
matplotlib = "^3.5.1"
nifty8 = {git = "https://gitlab.mpcdf.mpg.de/ift/nifty.git", branch = "NIFTy_8"}

[tool.poetry.extras]
degrid = ["ducc0", "sympy"]

[tool.poetry.scripts]
goquartical = 'quartical.executor:execute'
goquartical-config = 'quartical.config.parser:create_user_config'
goquartical-backup = 'quartical.apps.backup:backup'
goquartical-restore = 'quartical.apps.backup:restore'
goquartical-summary = 'quartical.apps.summary:summary'
goquartical-plot = 'quartical.apps.plotter:plot'

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
